/**
 * Sovereign Send — Per-User Solana Wallet with Atomic Protocol Fee
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  Every ICP identity gets a unique Solana wallet derived     │
 * │  via threshold Schnorr (ed25519). No seed phrase. No key.   │
 * │                                                             │
 * │  Every SOL transfer includes a 0.1% protocol fee — atomic,  │
 * │  built into the signed TX bytes, unforgeable.               │
 * ├─────────────────────────────────────────────────────────────┤
 * │                                                             │
 * │  SIGN-ONLY  (caller broadcasts, 0 canister cycle cost):     │
 * │  • signSend(to, amount, blockhash)     → signed TX + sig    │
 * │                                                             │
 * │  AUTONOMOUS  (canister does everything, ~500M cycle cost):  │
 * │  • sendSol(to, amount)                → TX broadcast by IC  │
 * │  • depositSol(target, amount)         → broadcast + deposit │
 * │                                                             │
 * ├─────────────────────────────────────────────────────────────┤
 * │  TARGETS:                                                   │
 * │  • ICP-SOL Swap  — send SOL, receive ICP at oracle rate     │
 * │  • SOL Borrow V3 — send SOL collateral, receive USDC loan   │
 * │  • mSOL (ckSOL)  — send SOL, receive mSOL (1:1 chain-key)   │
 * └─────────────────────────────────────────────────────────────┘
 *
 * CANISTER:  fxjsq-raaaa-aaaab-agdaa-cai
 * FEE:       0.1% (10 basis points) per signSend/sendSol
 * DEPOSIT:   0% fee (full amount goes to treasury)
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  SOLANA NETWORK FEE                                         │
 * │                                                             │
 * │  Every Solana transaction costs ~5,000-50,000 lamports in   │
 * │  network fees (paid to Solana validators, not to us).       │
 * │                                                             │
 * │  When sending near-full balance, subtract at least 50,000   │
 * │  lamports to avoid "insufficient lamports" errors.          │
 * │  Use maxSendLamports(balance) to calculate the safe max.    │
 * │                                                             │
 * │  This applies to both sendSol and depositSol.               │
 * └─────────────────────────────────────────────────────────────┘
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  PARTNER REVENUE SHARE                                      │
 * │                                                             │
 * │  Allowlisted partner dApps earn 20% of the protocol fee    │
 * │  generated by users transacting through their integration.  │
 * │                                                             │
 * │  Your users send, swap, or deposit through Sovereign Send   │
 * │  → 0.1% protocol fee is collected atomically               │
 * │  → 20% of that fee is attributed to your dApp              │
 * │                                                             │
 * │  To become a partner: register your canister principal via  │
 * │  addAllowedCaller, then contact team@meneseprotocol.io     │
 * │  for revenue share activation.                              │
 * └─────────────────────────────────────────────────────────────┘
 *
 * Made with love by Menese Protocol — https://meneseprotocol.io
 */

import { Actor, HttpAgent } from "@dfinity/agent";
import { Principal } from "@dfinity/principal";
import { IDL } from "@dfinity/candid";

// ═══════════════════════════════════════════════════════════════
//  CONSTANTS
// ═══════════════════════════════════════════════════════════════

const SOVEREIGN_SEND = "fxjsq-raaaa-aaaab-agdaa-cai";
const ICP_SOL_SWAP   = "w2vjc-2yaaa-aaaab-ae6zq-cai";
const SOL_BORROW_V3  = "p7teu-wyaaa-aaaab-afnvq-cai";
const CKSOL_MSOL     = "crmds-kqaaa-aaaaf-qf5aq-cai";  // mSOL canister (deposit SOL, mint mSOL)
const MSOL_LEDGER    = "2ykjj-eyaaa-aaaae-af4ma-cai";   // mSOL ICRC-2 ledger (balances, approve, transfer)
const IC_HOST        = "https://icp-api.io";

/**
 * Reserve 50,000 lamports for the Solana network fee.
 * Actual fees are typically 5,000-10,000 lamports, but we reserve
 * a larger margin to account for priority fees and fee spikes.
 */
export const SOLANA_NETWORK_FEE = 50_000n;

const SOLANA_RPCS = [
  "https://api.mainnet-beta.solana.com",
  "https://solana-rpc.publicnode.com",
  "https://solana.drpc.org",
  "https://rpc.ankr.com/solana",
];

// ═══════════════════════════════════════════════════════════════
//  CANDID IDL — matches deployed canister exactly
// ═══════════════════════════════════════════════════════════════

const sovereignSendIDL = ({ IDL }: any) => {
  const BorrowParams = IDL.Record({
    iasolExpected: IDL.Nat64, // internal param — handled by canister
    iausdToMint: IDL.Nat64,
    minUsdcOut: IDL.Nat64,
    userPubkey: IDL.Vec(IDL.Nat8),
    userUsdcAta: IDL.Vec(IDL.Nat8),
  });

  const TreasuryType = IDL.Variant({
    IcpSolSwap: IDL.Null,
    SolBorrow: IDL.Null,
    CkSol: IDL.Null,        // mSOL canister (crmds-kqaaa-aaaaf-qf5aq-cai)
  });

  return IDL.Service({
    getMyAddress: IDL.Func([], [IDL.Record({
      address: IDL.Text,
      publicKeyBytes: IDL.Vec(IDL.Nat8),
    })], []),

    getFeeTreasuryAddress: IDL.Func([], [IDL.Text], []),
    getAdmin: IDL.Func([], [IDL.Principal], ["query"]),
    getRegisteredTreasuries: IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))], ["query"]),
    init: IDL.Func([], [], []),

    registerTreasury: IDL.Func(
      [IDL.Principal, IDL.Text, TreasuryType],
      [IDL.Variant({ ok: IDL.Null, err: IDL.Text })],
      [],
    ),

    // Sign-only: caller provides blockhash, broadcasts TX themselves
    signSend: IDL.Func(
      [IDL.Text, IDL.Nat64, IDL.Text],
      [IDL.Variant({
        ok: IDL.Record({
          signedTxBase64: IDL.Text,
          sendAmount: IDL.Nat64,
          feeAmount: IDL.Nat64,
          txSignature: IDL.Text,
        }),
        err: IDL.Text,
      })],
      [],
    ),

    // Autonomous: canister fetches blockhash + broadcasts via HTTP outcall
    sendSol: IDL.Func(
      [IDL.Text, IDL.Nat64],
      [IDL.Variant({
        ok: IDL.Record({
          txSignature: IDL.Text,
          sendAmount: IDL.Nat64,
          feeAmount: IDL.Nat64,
        }),
        err: IDL.Text,
      })],
      [],
    ),

    depositSol: IDL.Func(
      [IDL.Principal, IDL.Nat64, IDL.Opt(BorrowParams)],
      [IDL.Variant({
        ok: IDL.Record({
          txSignature: IDL.Text,
          depositId: IDL.Nat,
        }),
        err: IDL.Text,
      })],
      [],
    ),

    // Sign-only deposit: caller provides blockhash, broadcasts TX themselves
    signDeposit: IDL.Func(
      [IDL.Principal, IDL.Nat64, IDL.Text, IDL.Opt(BorrowParams)],
      [IDL.Variant({
        ok: IDL.Record({
          signedTxBase64: IDL.Text,
          txSignature: IDL.Text,
          depositId: IDL.Nat,
        }),
        err: IDL.Text,
      })],
      [],
    ),

    // ── Derivation Shield (caller-pays economics) ──
    getShieldStatus: IDL.Func([], [IDL.Record({
      cycleBalance: IDL.Nat,
      minReserve: IDL.Nat,
      circuitBreakerActive: IDL.Bool,
      cachedUsers: IDL.Nat,
      allowlistSize: IDL.Nat,
      vouchedUsers: IDL.Nat,
      derivationFee: IDL.Nat,
      totalCyclesCollected: IDL.Nat,
      totalPaidDerivations: IDL.Nat,
    })], ["query"]),

    addAllowedCaller: IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ ok: IDL.Null, err: IDL.Text })],
      [],
    ),

    removeAllowedCaller: IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ ok: IDL.Null, err: IDL.Text })],
      [],
    ),

    // ── Partner User Registration ──
    // Allowlisted partner canisters can register their users' principals.
    // Registered users call sovereign_send directly from their frontend
    // — no inter-canister hop, faster execution.
    registerPartnerUsers: IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Variant({ ok: IDL.Nat, err: IDL.Text })],
      [],
    ),

    removePartnerUsers: IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Variant({ ok: IDL.Nat, err: IDL.Text })],
      [],
    ),
  });
};

// ═══════════════════════════════════════════════════════════════
//  TYPES
// ═══════════════════════════════════════════════════════════════

interface SignSendResult {
  signedTxBase64: string;
  sendAmount: bigint;
  feeAmount: bigint;
  txSignature: string;
}

interface AutonomousSendResult {
  txSignature: string;
  sendAmount: bigint;
  feeAmount: bigint;
}

interface AutonomousDepositResult {
  txSignature: string;
  depositId: bigint;
}

// ═══════════════════════════════════════════════════════════════
//  ACTOR FACTORY
// ═══════════════════════════════════════════════════════════════

/**
 * Create an authenticated Sovereign Send actor.
 * Pass the identity from AuthClient.getIdentity().
 */
export function createSovereignSendActor(identity: any) {
  const agent = new HttpAgent({ host: IC_HOST, identity });
  return Actor.createActor(sovereignSendIDL, {
    agent,
    canisterId: SOVEREIGN_SEND,
  });
}

// ═══════════════════════════════════════════════════════════════
//  SOLANA HELPERS (for sign-only path)
// ═══════════════════════════════════════════════════════════════

/** Fetch a recent Solana blockhash. Tries RPCs with sequential fallback. */
export async function fetchSolanaBlockhash(): Promise<string> {
  for (const rpc of SOLANA_RPCS) {
    try {
      const res = await fetch(rpc, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          jsonrpc: "2.0", id: 1,
          method: "getLatestBlockhash",
          params: [{ commitment: "confirmed" }],
        }),
      });
      const json = await res.json();
      if (json.result?.value?.blockhash) return json.result.value.blockhash;
    } catch { continue; }
  }
  throw new Error("Failed to fetch Solana blockhash from all RPCs");
}

/**
 * Broadcast a base64-encoded signed Solana TX. Returns TX signature.
 *
 * Sends to ALL RPCs in parallel via Promise.any — Solana transactions
 * are idempotent (same TX submitted twice = same result), so it is safe
 * and faster to broadcast to multiple RPCs simultaneously.
 */
export async function broadcastSolanaTx(signedTxBase64: string): Promise<string> {
  const attempts = SOLANA_RPCS.map(async (rpc) => {
    const res = await fetch(rpc, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        jsonrpc: "2.0", id: 1,
        method: "sendTransaction",
        params: [signedTxBase64, { encoding: "base64", skipPreflight: true }],
      }),
    });
    const json = await res.json();
    if (json.result) return json.result as string;
    throw new Error(json.error?.message ?? "No result from RPC");
  });

  try {
    return await Promise.any(attempts);
  } catch {
    throw new Error("Broadcast failed on all RPCs");
  }
}

/** Convert SOL amount (e.g. 0.5) to lamports (500_000_000). */
export function solToLamports(sol: number): bigint {
  return BigInt(Math.round(sol * 1_000_000_000));
}

/**
 * Calculate the maximum sendable lamports after reserving for the Solana network fee.
 *
 * Every Solana TX costs ~5,000-50,000 lamports in validator fees.
 * When sending your full balance, subtract this reserve to avoid
 * "insufficient lamports for rent" or "insufficient funds" errors.
 *
 * @param balanceLamports - Current wallet balance in lamports
 * @returns Maximum lamports you can send/deposit safely
 *
 * Example:
 *   const balance = 1_500_000_000n; // 1.5 SOL
 *   const max = maxSendLamports(balance); // 1_499_950_000n (1.5 SOL - 50k fee)
 */
export function maxSendLamports(balanceLamports: bigint): bigint {
  if (balanceLamports <= SOLANA_NETWORK_FEE) return 0n;
  return balanceLamports - SOLANA_NETWORK_FEE;
}

/** Convert lamports to SOL for display (e.g. 1_500_000_000 -> 1.5). */
export function lamportsToSol(lamports: bigint): number {
  return Number(lamports) / 1_000_000_000;
}

// ═══════════════════════════════════════════════════════════════
//  API — The operations developers use
// ═══════════════════════════════════════════════════════════════

/**
 * Get the caller's derived Solana address.
 * First call derives via IC threshold Schnorr (~4s).
 * Second call returns from cache (~2s).
 *
 * Fund this address with SOL before calling any send/deposit.
 */
export async function getMyAddress(actor: any): Promise<{ address: string; publicKeyBytes: Uint8Array }> {
  const result = await actor.getMyAddress();
  return { address: result.address, publicKeyBytes: new Uint8Array(result.publicKeyBytes) };
}

/**
 * SIGN-ONLY SEND — Transfer SOL to any Solana address.
 *
 * The canister signs an atomic TX with two instructions:
 *   IX1: Transfer 99.9% to your destination
 *   IX2: Transfer 0.1% to the protocol fee treasury
 *
 * You provide the blockhash and broadcast the TX yourself.
 * This is the cheapest path — 0 canister cycles for broadcast.
 *
 * NOTE: When sending near-full balance, use maxSendLamports() to
 * reserve enough for the Solana network fee (~50,000 lamports).
 *
 * Flow:
 *   1. fetchSolanaBlockhash() from any Solana RPC
 *   2. signSend(destination, lamports, blockhash) -> signed TX
 *   3. broadcastSolanaTx(signedTxBase64) -> TX lands on Solana
 */
export async function signSend(
  actor: any,
  toAddress: string,
  solAmount: number,
): Promise<{ txSignature: string; signedTxBase64: string; sendAmount: bigint; feeAmount: bigint }> {
  const blockhash = await fetchSolanaBlockhash();
  const lamports = solToLamports(solAmount);

  const result = await actor.signSend(toAddress, lamports, blockhash);
  if ("err" in result) throw new Error(result.err);

  const { signedTxBase64, sendAmount, feeAmount, txSignature } = result.ok;

  // Broadcast from browser (0 canister cycles)
  await broadcastSolanaTx(signedTxBase64);

  return { txSignature, signedTxBase64, sendAmount, feeAmount };
}

/**
 * AUTONOMOUS SEND — Transfer SOL, canister handles everything.
 *
 * One call. The canister:
 *   1. Fetches a fresh Solana blockhash via HTTP outcall
 *   2. Signs the atomic TX (destination + 0.1% fee)
 *   3. Broadcasts to Solana RPCs in parallel
 *
 * Higher cycle cost (~500M) but simplest integration.
 * No Solana RPC handling needed on your end.
 *
 * NOTE: When sending near-full balance, use maxSendLamports() to
 * reserve enough for the Solana network fee (~50,000 lamports).
 */
export async function sendSol(
  actor: any,
  toAddress: string,
  solAmount: number,
): Promise<AutonomousSendResult> {
  const lamports = solToLamports(solAmount);
  const result = await actor.sendSol(toAddress, lamports);
  if ("err" in result) throw new Error(result.err);
  return result.ok;
}

/**
 * AUTONOMOUS DEPOSIT — Send SOL to a registered treasury.
 *
 * One call. The canister:
 *   1. Fetches Solana blockhash via HTTP outcall
 *   2. Signs TX sending SOL to target treasury
 *   3. Broadcasts to Solana RPCs
 *   4. Calls target canister's expectDeposit
 *
 * Supported targets:
 *   - ICP-SOL Swap (w2vjc): you send SOL, receive ICP at oracle rate
 *   - SOL Borrow V3 (p7teu): you send SOL collateral, receive USDC loan
 *
 * You receive ICP/USDC automatically after Solana confirms.
 *
 * NOTE: When depositing near-full balance, use maxSendLamports() to
 * reserve enough for the Solana network fee (~50,000 lamports).
 *
 * @param actor - Sovereign Send actor
 * @param targetCanisterId - Target treasury canister ID (e.g. ICP_SOL_SWAP or SOL_BORROW_V3)
 * @param solAmount - Amount of SOL to deposit (human-readable, e.g. 0.5)
 * @param borrowParams - Optional. Required only for SOL Borrow V3 deposits.
 */
export async function depositSol(
  actor: any,
  targetCanisterId: string,
  solAmount: number,
  borrowParams?: {
    iasolExpected: bigint;
    iausdToMint: bigint;
    minUsdcOut: bigint;
    userPubkey: Uint8Array;
    userUsdcAta: Uint8Array;
  },
): Promise<AutonomousDepositResult> {
  const lamports = solToLamports(solAmount);
  const bpOpt = borrowParams
    ? [{
        iasolExpected: borrowParams.iasolExpected,
        iausdToMint: borrowParams.iausdToMint,
        minUsdcOut: borrowParams.minUsdcOut,
        userPubkey: Array.from(borrowParams.userPubkey),
        userUsdcAta: Array.from(borrowParams.userUsdcAta),
      }]
    : [];
  const result = await actor.depositSol(
    Principal.fromText(targetCanisterId),
    lamports,
    bpOpt,
  );
  if ("err" in result) throw new Error(result.err);
  return result.ok;
}

// ═══════════════════════════════════════════════════════════════
//  SHORTCUT FUNCTIONS — Named by what you get back
// ═══════════════════════════════════════════════════════════════

/** Send SOL, receive ICP at oracle rate. Autonomous — one call. */
export async function solToIcp(actor: any, solAmount: number) {
  return depositSol(actor, ICP_SOL_SWAP, solAmount);
}

/**
 * Send SOL, receive ICP. Sign-only style — but uses autonomous depositSol
 * under the hood since deposits have no sign-only variant in the canister.
 */
export async function signSolToIcp(actor: any, solAmount: number) {
  return depositSol(actor, ICP_SOL_SWAP, solAmount);
}

// ═══════════════════════════════════════════════════════════════
//  VERIFICATION TEST — Call this to confirm your integration works
// ═══════════════════════════════════════════════════════════════

/**
 * Run a basic integration test:
 *   1. Derives your Solana address
 *   2. Checks the fee treasury address
 *   3. Lists registered treasuries
 *
 * Does NOT send any SOL — safe to call anytime.
 */
export async function verifyIntegration(actor: any): Promise<{
  myAddress: string;
  feeTreasury: string;
  treasuries: [string, string][];
}> {
  const [addr, fee, treasuries] = await Promise.all([
    actor.getMyAddress(),
    actor.getFeeTreasuryAddress(),
    actor.getRegisteredTreasuries(),
  ]);

  const result = {
    myAddress: addr.address,
    feeTreasury: fee,
    treasuries: treasuries.map(([p, sol]: [any, string]) => [p.toText(), sol]),
  };

  console.log("Sovereign Send Integration Verified");
  console.log("  Your SOL address:", result.myAddress);
  console.log("  Fee treasury:", result.feeTreasury);
  console.log("  Registered treasuries:", result.treasuries.length);
  for (const [canister, solAddr] of result.treasuries) {
    console.log("    ", canister, "->", solAddr.slice(0, 12) + "...");
  }

  return result;
}

// ═══════════════════════════════════════════════════════════════
//  DERIVATION SHIELD — Cycle Drain Protection
// ═══════════════════════════════════════════════════════════════
//
//  3-layer defense against cycle drain attacks on getMyAddress():
//
//  Layer 1: Circuit Breaker — hard stop when canister cycles < 500B.
//           Even under attack, existing cached users keep working.
//
//  Layer 2: Global Throttle — max 20 new address derivations per 60s.
//           Sliding window. Legitimate apps onboard 1-5 users/min.
//           Attacker burns at most 600B cycles/min (survivable).
//
//  Layer 3: Caller Allowlist — your canister principal bypasses the
//           throttle (but NOT the circuit breaker). Register via
//           addAllowedCaller(principal).
//
//  Cached callers (anyone who called getMyAddress before) bypass
//  ALL layers — zero overhead on repeat calls.

export interface ShieldStatus {
  cycleBalance: bigint;
  minReserve: bigint;
  circuitBreakerActive: boolean;
  cachedUsers: bigint;
  allowlistSize: bigint;
  vouchedUsers: bigint;
  derivationFee: bigint;
  totalCyclesCollected: bigint;
  totalPaidDerivations: bigint;
}

/**
 * Register user principals for direct frontend access.
 *
 * Your backend canister (allowlisted) calls this to vouch for your users.
 * After registration, those users call sovereign_send directly from
 * their browser — no inter-canister hop, faster execution.
 *
 * @param actor - Sovereign Send actor (must be called from allowlisted canister)
 * @param userPrincipals - Array of user principal IDs to register
 * @returns Number of newly registered users
 *
 * Limits: max 50,000 vouched users per partner canister.
 * Partners can only remove users they registered.
 */
export async function registerPartnerUsers(
  actor: any,
  userPrincipals: Principal[],
): Promise<number> {
  const result = await actor.registerPartnerUsers(userPrincipals);
  if ("err" in result) throw new Error(result.err);
  return Number(result.ok);
}

/** Remove previously registered user principals. */
export async function removePartnerUsers(
  actor: any,
  userPrincipals: Principal[],
): Promise<number> {
  const result = await actor.removePartnerUsers(userPrincipals);
  if ("err" in result) throw new Error(result.err);
  return Number(result.ok);
}

/** Query the canister's Derivation Shield status — free, no auth needed. */
export async function getShieldStatus(actor: any): Promise<ShieldStatus> {
  return actor.getShieldStatus();
}

// ═══════════════════════════════════════════════════════════════
//  mSOL (ckSOL) — Yield-Bearing Staked SOL on ICP
// ═══════════════════════════════════════════════════════════════
//
//  mSOL is a chain-key representation of SOL on the Internet Computer.
//  Deposit SOL → receive mSOL (1:1 rate). Redeem mSOL → receive SOL back.
//
//  Canister:  crmds-kqaaa-aaaaf-qf5aq-cai  (mSOL minting + redemption)
//  Ledger:    2ykjj-eyaaa-aaaae-af4ma-cai  (ICRC-2 token — balances, transfers, approvals)
//
//  ┌─────────────────────────────────────────────────────────────┐
//  │  DEPOSIT FLOW  (SOL → mSOL):                                │
//  │                                                             │
//  │  1. Use Sovereign Send to transfer SOL to the mSOL treasury │
//  │  2. Call expectCkSolDeposit(txHash, lamports) on mSOL       │
//  │  3. Canister verifies TX on Solana, mints mSOL to you       │
//  │                                                             │
//  │  Fee: 0.1% deposit fee (10 bps) deducted from mint amount   │
//  │  Min deposit: 0.05 SOL (50,000,000 lamports)                │
//  │  Verification: ~10-20 seconds (auto-checked by canister)    │
//  ├─────────────────────────────────────────────────────────────┤
//  │  REDEEM FLOW  (mSOL → SOL):                                 │
//  │                                                             │
//  │  1. icrc2_approve mSOL ledger → mSOL canister as spender    │
//  │  2. Call requestCkSolRedemption(amount, solDestination)      │
//  │  3. Canister burns mSOL, signs SOL TX, broadcasts to Solana │
//  │                                                             │
//  │  Fee: 0.1% redemption fee (10 bps) deducted from SOL out    │
//  │  Min redemption: 0.05 SOL after fee                         │
//  │  SOL arrives: ~30-60 seconds after redemption request        │
//  └─────────────────────────────────────────────────────────────┘

export { CKSOL_MSOL, MSOL_LEDGER };

// ── mSOL Canister IDL ─────────────────────────────────────────

const msolCanisterIDL = ({ IDL }: any) => {
  return IDL.Service({
    expectCkSolDeposit: IDL.Func(
      [IDL.Text, IDL.Nat64, IDL.Opt(IDL.Principal)],
      [IDL.Variant({ ok: IDL.Nat, err: IDL.Text })],
      [],
    ),
    requestCkSolRedemption: IDL.Func(
      [IDL.Nat64, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({
        ok: IDL.Record({
          redemptionId: IDL.Nat,
          signedTxBase64: IDL.Text,
          signatureBase58: IDL.Text,
        }),
        err: IDL.Text,
      })],
      [],
    ),
    getCksolStats: IDL.Func([], [IDL.Record({
      stakePct: IDL.Nat,
      totalYieldEarned: IDL.Nat64,
      pendingRedemptions: IDL.Nat,
      stakedIasolLamports: IDL.Nat64,
      pendingDeposits: IDL.Nat,
      estimatedApyBps: IDL.Nat,
      currentEpoch: IDL.Nat,
      solPerCkSolE9: IDL.Nat64,
      idleSolLamports: IDL.Nat64,
      totalRedemptions: IDL.Nat,
      totalCkSolSupply: IDL.Nat64,
      totalProtocolFees: IDL.Nat64,
      totalDeposits: IDL.Nat,
      totalSolBackingLamports: IDL.Nat64,
    })], []),
    getCksolRate: IDL.Func([], [IDL.Record({
      epoch: IDL.Nat,
      totalBackingLamports: IDL.Nat64,
      solPerCkSolE9: IDL.Nat64,
      totalCkSolSupply: IDL.Nat64,
      iasolToSolRateE9: IDL.Nat64,
    })], []),
    getSolanaAddress: IDL.Func([], [IDL.Record({
      publicKey: IDL.Vec(IDL.Nat8),
      address: IDL.Text,
    })], []),
  });
};

// ── ICRC-2 Ledger IDL (for approve + balance) ────────────────

const icrc2LedgerIDL = ({ IDL }: any) => {
  const Account = IDL.Record({
    owner: IDL.Principal,
    subaccount: IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const ApproveArgs = IDL.Record({
    from_subaccount: IDL.Opt(IDL.Vec(IDL.Nat8)),
    spender: Account,
    amount: IDL.Nat,
    expected_allowance: IDL.Opt(IDL.Nat),
    expires_at: IDL.Opt(IDL.Nat64),
    fee: IDL.Opt(IDL.Nat),
    memo: IDL.Opt(IDL.Vec(IDL.Nat8)),
    created_at_time: IDL.Opt(IDL.Nat64),
  });
  const ApproveError = IDL.Variant({
    BadFee: IDL.Record({ expected_fee: IDL.Nat }),
    InsufficientFunds: IDL.Record({ balance: IDL.Nat }),
    AllowanceChanged: IDL.Record({ current_allowance: IDL.Nat }),
    Expired: IDL.Record({ ledger_time: IDL.Nat64 }),
    TemporarilyUnavailable: IDL.Null,
    GenericError: IDL.Record({ error_code: IDL.Nat, message: IDL.Text }),
  });
  return IDL.Service({
    icrc1_balance_of: IDL.Func([Account], [IDL.Nat], ["query"]),
    icrc1_total_supply: IDL.Func([], [IDL.Nat], ["query"]),
    icrc1_fee: IDL.Func([], [IDL.Nat], ["query"]),
    icrc2_approve: IDL.Func([ApproveArgs], [IDL.Variant({ Ok: IDL.Nat, Err: ApproveError })], []),
  });
};

// ── mSOL Actor Factories ─────────────────────────────────────

/** Create mSOL canister actor (for deposit/redeem). Requires authenticated identity. */
export function createMsolActor(identity: any) {
  const agent = new HttpAgent({ host: IC_HOST, identity });
  return Actor.createActor(msolCanisterIDL, {
    agent,
    canisterId: CKSOL_MSOL,
  });
}

/** Create mSOL ledger actor (for balance/approve). Requires authenticated identity. */
export function createMsolLedgerActor(identity: any) {
  const agent = new HttpAgent({ host: IC_HOST, identity });
  return Actor.createActor(icrc2LedgerIDL, {
    agent,
    canisterId: MSOL_LEDGER,
  });
}

// ── mSOL Types ────────────────────────────────────────────────

export interface MsolDepositResult {
  depositId: bigint;
}

export interface MsolRedemptionResult {
  redemptionId: bigint;
  signedTxBase64: string;
  signatureBase58: string;
}

export interface MsolStats {
  solPerCkSolE9: bigint;
  totalSolBackingLamports: bigint;
  totalCkSolSupply: bigint;
  pendingDeposits: bigint;
  pendingRedemptions: bigint;
  totalDeposits: bigint;
  totalRedemptions: bigint;
}

// ── mSOL API ─────────────────────────────────────────────────

/**
 * Get your mSOL balance.
 *
 * @param ledgerActor - from createMsolLedgerActor(identity)
 * @param principalText - your principal as text (identity.getPrincipal().toText())
 * @returns balance in mSOL lamports (9 decimals, same as SOL)
 */
export async function getMsolBalance(
  ledgerActor: any,
  principalText: string,
): Promise<bigint> {
  return ledgerActor.icrc1_balance_of({
    owner: Principal.fromText(principalText),
    subaccount: [],
  }) as Promise<bigint>;
}

/**
 * DEPOSIT SOL → MINT mSOL
 *
 * Full flow:
 *   1. Send SOL to the mSOL treasury via Sovereign Send
 *   2. Call expectCkSolDeposit with the Solana TX hash
 *   3. Canister verifies the TX on-chain and mints mSOL to your principal
 *
 * The canister auto-verifies every 10 seconds (up to 20 attempts).
 * mSOL appears in your balance within ~10-30 seconds.
 *
 * NOTE: The canister uses the actual on-chain amount for minting,
 * so network fees (auto-clamped by Sovereign Send) are handled automatically.
 *
 * @param sovereignActor - from createSovereignSendActor(identity)
 * @param msolActor - from createMsolActor(identity)
 * @param solAmount - amount of SOL to deposit (human-readable, e.g. 0.5)
 * @returns depositId — track status via myCksolDeposits()
 *
 * @example
 *   const ss = createSovereignSendActor(identity);
 *   const msol = createMsolActor(identity);
 *   const { depositId, txSignature } = await depositSolForMsol(ss, msol, 0.1);
 *   // mSOL minted to your principal within ~30s
 */
export async function depositSolForMsol(
  sovereignActor: any,
  msolActor: any,
  solAmount: number,
): Promise<{ depositId: bigint; txSignature: string }> {
  const lamports = solToLamports(solAmount);

  // Step 1: Send SOL to mSOL treasury via Sovereign Send (autonomous path)
  const depositResult = await sovereignActor.depositSol(
    Principal.fromText(CKSOL_MSOL),
    lamports,
    [], // no borrow params
  );
  if ("err" in depositResult) throw new Error(depositResult.err);
  const txSignature = depositResult.ok.txSignature as string;

  // Step 2: Register the deposit with the mSOL canister
  // Pass the actual lamports — canister verifies on-chain amount (may be less due to network fee)
  const expectResult = await msolActor.expectCkSolDeposit(
    txSignature,
    lamports,
    [], // onBehalfOf: null (mints to caller)
  );
  if ("err" in expectResult) throw new Error(expectResult.err);

  return {
    depositId: expectResult.ok as bigint,
    txSignature,
  };
}

/**
 * DEPOSIT SOL → MINT mSOL (Sign-Only Path)
 *
 * Same as depositSolForMsol but uses sign-only for the Solana TX.
 * Cheaper (0 canister cycles for broadcast) but you handle the RPC.
 *
 * @example
 *   const ss = createSovereignSendActor(identity);
 *   const msol = createMsolActor(identity);
 *   const { depositId, txSignature } = await signDepositSolForMsol(ss, msol, 0.1);
 */
export async function signDepositSolForMsol(
  sovereignActor: any,
  msolActor: any,
  solAmount: number,
): Promise<{ depositId: bigint; txSignature: string }> {
  const lamports = solToLamports(solAmount);

  // Step 1: Get mSOL treasury address
  const treasury = await msolActor.getSolanaAddress();
  const treasuryAddress = treasury.address as string;

  // Step 2: Sign SOL transfer via Sovereign Send (sign-only)
  const blockhash = await fetchSolanaBlockhash();
  const signResult = await sovereignActor.signSend(treasuryAddress, lamports, blockhash);
  if ("err" in signResult) throw new Error(signResult.err);

  const { signedTxBase64, txSignature } = signResult.ok;

  // Step 3: Broadcast from browser
  await broadcastSolanaTx(signedTxBase64);

  // Step 4: Register deposit with mSOL canister
  const expectResult = await msolActor.expectCkSolDeposit(
    txSignature,
    lamports,
    [], // onBehalfOf: null
  );
  if ("err" in expectResult) throw new Error(expectResult.err);

  return {
    depositId: expectResult.ok as bigint,
    txSignature,
  };
}

/**
 * REDEEM mSOL → RECEIVE SOL
 *
 * Full flow:
 *   1. Approve mSOL canister to spend your mSOL (icrc2_approve on ledger)
 *   2. Call requestCkSolRedemption with amount + your SOL destination
 *   3. Canister burns mSOL, signs SOL transfer, broadcasts to Solana
 *
 * IMPORTANT: You must call icrc2_approve BEFORE calling this function.
 * Use approveMsolForRedemption() helper or do it manually.
 *
 * @param msolActor - from createMsolActor(identity)
 * @param msolLamports - amount of mSOL to redeem (in lamports, 9 decimals)
 * @param solDestination - Solana address to receive SOL (base58)
 * @returns redemptionId + TX signature for tracking
 *
 * @example
 *   const msol = createMsolActor(identity);
 *   const ledger = createMsolLedgerActor(identity);
 *
 *   // Step 1: Approve (include fee buffer)
 *   await approveMsolForRedemption(ledger, 100_000_000n); // 0.1 mSOL
 *
 *   // Step 2: Redeem
 *   const result = await redeemMsolForSol(msol, 100_000_000n, "YourSolanaAddress...");
 *   console.log("SOL arriving at:", result.signatureBase58);
 */
export async function redeemMsolForSol(
  msolActor: any,
  msolLamports: bigint,
  solDestination: string,
): Promise<MsolRedemptionResult> {
  const result = await msolActor.requestCkSolRedemption(
    msolLamports,
    solDestination,
    [], // recentBlockhash: null (canister fetches)
  );
  if ("err" in result) throw new Error(result.err);
  return {
    redemptionId: result.ok.redemptionId,
    signedTxBase64: result.ok.signedTxBase64,
    signatureBase58: result.ok.signatureBase58,
  };
}

/**
 * APPROVE mSOL canister to burn your mSOL for redemption.
 *
 * Must be called before redeemMsolForSol(). Approves the mSOL canister
 * as a spender on the ICRC-2 ledger. Includes a 100,000 buffer for the
 * ledger transfer fee.
 *
 * @param ledgerActor - from createMsolLedgerActor(identity)
 * @param msolLamports - amount of mSOL to approve for redemption
 *
 * @example
 *   const ledger = createMsolLedgerActor(identity);
 *   await approveMsolForRedemption(ledger, 100_000_000n); // approve 0.1 mSOL
 */
export async function approveMsolForRedemption(
  ledgerActor: any,
  msolLamports: bigint,
): Promise<void> {
  const fee = await ledgerActor.icrc1_fee() as bigint;
  const approveAmount = msolLamports + fee + 100_000n; // buffer for fee

  const result = await ledgerActor.icrc2_approve({
    from_subaccount: [],
    spender: {
      owner: Principal.fromText(CKSOL_MSOL),
      subaccount: [],
    },
    amount: approveAmount,
    expected_allowance: [],
    expires_at: [],
    fee: [fee],
    memo: [],
    created_at_time: [],
  });

  if ("Err" in result) {
    const err = result.Err;
    if ("InsufficientFunds" in err) throw new Error(`Insufficient mSOL. Balance: ${err.InsufficientFunds.balance}`);
    if ("BadFee" in err) throw new Error(`Bad fee. Expected: ${err.BadFee.expected_fee}`);
    throw new Error(`Approve failed: ${Object.keys(err)[0]}`);
  }
}

/**
 * Get mSOL canister stats (rate, backing, supply).
 */
export async function getMsolStats(msolActor: any): Promise<MsolStats> {
  return msolActor.getCksolStats();
}

/**
 * Shortcut: Deposit SOL, receive mSOL. Autonomous path.
 * Equivalent to depositSolForMsol() with friendlier name.
 */
export async function solToMsol(
  sovereignActor: any,
  msolActor: any,
  solAmount: number,
) {
  return depositSolForMsol(sovereignActor, msolActor, solAmount);
}

/**
 * Shortcut: Burn mSOL, receive SOL. Includes approve step.
 *
 * @example
 *   const msol = createMsolActor(identity);
 *   const ledger = createMsolLedgerActor(identity);
 *   await msolToSol(msol, ledger, 100_000_000n, "YourSolAddress...");
 */
export async function msolToSol(
  msolActor: any,
  ledgerActor: any,
  msolLamports: bigint,
  solDestination: string,
) {
  await approveMsolForRedemption(ledgerActor, msolLamports);
  return redeemMsolForSol(msolActor, msolLamports, solDestination);
}
